-- ============================================================
-- V14: Tạo bảng departments + seed data
-- ============================================================

CREATE TABLE departments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(20) NOT NULL UNIQUE,
    name            VARCHAR(120) NOT NULL,
    description     VARCHAR(500),
    manager_id      BIGINT,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_departments_manager ON departments(manager_id);

COMMENT ON TABLE departments IS 'Phòng ban trong công ty';
COMMENT ON COLUMN departments.code IS 'Mã phòng ban (VD: IT, HR, SALE)';
COMMENT ON COLUMN departments.name IS 'Tên đầy đủ phòng ban';
COMMENT ON COLUMN departments.manager_id IS 'Trưởng phòng của phòng ban này';

-- Seed departments (không có manager_id, sẽ update sau khi có users)
INSERT INTO departments (code, name, description, enabled) VALUES
('EXEC', 'Ban Giám đốc', 'Ban Giám đốc công ty - Quản lý cao nhất', TRUE),
('IT', 'Phòng Công nghệ thông tin', 'Quản lý hệ thống IT, infrastructure, hỗ trợ kỹ thuật', TRUE),
('HR', 'Phòng Nhân sự', 'Tuyển dụng, đào tạo, chính sách nhân sự', TRUE),
('SALE', 'Phòng Kinh doanh', 'Bán hàng, chăm sóc khách hàng, phát triển kinh doanh', TRUE),
('MKT', 'Phòng Marketing', 'Marketing, truyền thông, xây dựng thương hiệu', TRUE),
('FIN', 'Phòng Tài chính - Kế toán', 'Tài chính, kế toán, thuế, quản lý chi phí', TRUE);
