-- ============================================================
-- V32: Tạo bảng teams - Nhóm IT theo chức năng
-- ============================================================
-- VD: Network Team, Hardware Team, Software Team...

CREATE TABLE teams (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(120) NOT NULL,
    code            VARCHAR(20) NOT NULL UNIQUE,
    description     VARCHAR(500),
    department_id   BIGINT NOT NULL REFERENCES departments(id),
    lead_id         BIGINT REFERENCES users(id),
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uk_team_code UNIQUE (code),
    CONSTRAINT uk_team_name_dept UNIQUE (name, department_id)
);

-- Indexes cho performance
CREATE INDEX idx_teams_department ON teams(department_id);
CREATE INDEX idx_teams_lead ON teams(lead_id);
CREATE INDEX idx_teams_enabled ON teams(enabled);

COMMENT ON TABLE teams IS 'Nhóm IT theo chức năng (VD: Network, Hardware, Software)';
COMMENT ON COLUMN teams.code IS 'Mã team (VD: NET, HW, SW)';
COMMENT ON COLUMN teams.lead_id IS 'Trưởng nhóm';

-- Seed default IT teams
INSERT INTO teams (name, code, description, department_id, enabled) VALUES
('Network Team', 'NET', 'Quản lý mạng, Wi-Fi, VPN, Internet', (SELECT id FROM departments WHERE code = 'IT'), TRUE),
('Hardware Team', 'HW', 'Quản lý máy tính, thiết bị, phần cứng', (SELECT id FROM departments WHERE code = 'IT'), TRUE),
('Software Team', 'SW', 'Quản lý phần mềm, cài đặt, license', (SELECT id FROM departments WHERE code = 'IT'), TRUE),
('Security Team', 'SEC', 'Bảo mật, firewall, access control', (SELECT id FROM departments WHERE code = 'IT'), TRUE),
('General Support', 'GEN', 'Hỗ trợ chung, mixed issues', (SELECT id FROM departments WHERE code = 'IT'), TRUE);

-- Set team leads (optional - can be updated later)
-- UPDATE teams SET lead_id = (SELECT id FROM users WHERE username = 'tech.smith') WHERE code = 'NET';
