-- ============================================================
-- V33: Tạo bảng categories - Phân loại ticket có subcategory
-- ============================================================
-- Thiết kế self-referential để hỗ trợ category/subcategory

CREATE TABLE categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(120) NOT NULL,
    code            VARCHAR(20) NOT NULL UNIQUE,
    description     VARCHAR(500),
    parent_id       BIGINT REFERENCES categories(id),
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    display_order  INT DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uk_category_code UNIQUE (code),
    CONSTRAINT uk_category_name_parent UNIQUE (name, parent_id)
);

-- Indexes cho performance
CREATE INDEX idx_categories_parent ON categories(parent_id);
CREATE INDEX idx_categories_enabled ON categories(enabled);

COMMENT ON TABLE categories IS 'Phân loại ticket: Category và Subcategory';
COMMENT ON COLUMN categories.parent_id IS 'Parent category (NULL = top-level category)';

-- Seed top-level categories (không có parent)
INSERT INTO categories (name, code, description, parent_id, display_order) VALUES
('Software', 'SOFTWARE', 'Các vấn đề liên quan đến phần mềm, ứng dụng', NULL, 1),
('Hardware', 'HARDWARE', 'Các vấn đề liên quan đến máy tính, thiết bị', NULL, 2),
('Network', 'NETWORK', 'Các vấn đề liên quan đến mạng, Wi-Fi, VPN', NULL, 3),
('Account', 'ACCOUNT', 'Các vấn đề liên quan đến tài khoản, đăng nhập', NULL, 4),
('Email', 'EMAIL', 'Các vấn đề liên quan đến email', NULL, 5),
('Security', 'SECURITY', 'Các vấn đề liên quan đến bảo mật', NULL, 6),
('Other', 'OTHER', 'Các vấn đề khác', NULL, 7);

-- Seed subcategories cho Network
INSERT INTO categories (name, code, description, parent_id, display_order) VALUES
('Wi-Fi', 'WIFI', 'Sự cố Wi-Fi, kết nối wireless', (SELECT id FROM categories WHERE code = 'NETWORK'), 1),
('LAN', 'LAN', 'Sự cố mạng LAN, cáp mạng', (SELECT id FROM categories WHERE code = 'NETWORK'), 2),
('VPN', 'VPN', 'Sự cố kết nối VPN từ xa', (SELECT id FROM categories WHERE code = 'NETWORK'), 3),
('Internet', 'INTERNET', 'Sự cố đường truyền internet', (SELECT id FROM categories WHERE code = 'NETWORK'), 4),
('Firewall', 'FIREWALL', 'Cấu hình firewall, port', (SELECT id FROM categories WHERE code = 'NETWORK'), 5);

-- Seed subcategories cho Hardware
INSERT INTO categories (name, code, description, parent_id, display_order) VALUES
('Computer', 'COMPUTER', 'Máy tính, laptop, PC', (SELECT id FROM categories WHERE code = 'HARDWARE'), 1),
('Printer', 'PRINTER', 'Máy in, scanner', (SELECT id FROM categories WHERE code = 'HARDWARE'), 2),
('Monitor', 'MONITOR', 'Màn hình', (SELECT id FROM categories WHERE code = 'HARDWARE'), 3),
('Keyboard/Mouse', 'INPUT', 'Bàn phím, chuột', (SELECT id FROM categories WHERE code = 'HARDWARE'), 4),
('Peripheral', 'PERIPHERAL', 'Các thiết bị ngoại vi khác', (SELECT id FROM categories WHERE code = 'HARDWARE'), 5);

-- Seed subcategories cho Software
INSERT INTO categories (name, code, description, parent_id, display_order) VALUES
('Installation', 'INSTALL', 'Cài đặt phần mềm mới', (SELECT id FROM categories WHERE code = 'SOFTWARE'), 1),
('License', 'LICENSE', 'Vấn đề license, activation', (SELECT id FROM categories WHERE code = 'SOFTWARE'), 2),
('Application Error', 'APP_ERROR', 'Lỗi ứng dụng, crash', (SELECT id FROM categories WHERE code = 'SOFTWARE'), 3),
('Update', 'UPDATE', 'Cập nhật phần mềm', (SELECT id FROM categories WHERE code = 'SOFTWARE'), 4),
('Configuration', 'CONFIG', 'Cấu hình phần mềm', (SELECT id FROM categories WHERE code = 'SOFTWARE'), 5);

-- Seed subcategories cho Account
INSERT INTO categories (name, code, description, parent_id, display_order) VALUES
('Password Reset', 'PASSWORD', 'Reset mật khẩu', (SELECT id FROM categories WHERE code = 'ACCOUNT'), 1),
('New Account', 'NEW_ACCOUNT', 'Tạo tài khoản mới', (SELECT id FROM categories WHERE code = 'ACCOUNT'), 2),
('Access Control', 'ACCESS', 'Phân quyền truy cập', (SELECT id FROM categories WHERE code = 'ACCOUNT'), 3),
('Account Locked', 'LOCKED', 'Tài khoản bị khóa', (SELECT id FROM categories WHERE code = 'ACCOUNT'), 4);

-- Seed subcategories cho Email
INSERT INTO categories (name, code, description, parent_id, display_order) VALUES
('Setup', 'EMAIL_SETUP', 'Cài đặt email client', (SELECT id FROM categories WHERE code = 'EMAIL'), 1),
('Sync', 'EMAIL_SYNC', 'Đồng bộ email', (SELECT id FROM categories WHERE code = 'EMAIL'), 2),
('Send/Receive', 'EMAIL_SR', 'Không gửi/nhận được email', (SELECT id FROM categories WHERE code = 'EMAIL'), 3),
('Storage', 'EMAIL_STORAGE', 'Hộp thư đầy, lưu trữ', (SELECT id FROM categories WHERE code = 'EMAIL'), 4);

-- Seed subcategories cho Security
INSERT INTO categories (name, code, description, parent_id, display_order) VALUES
('Virus/Malware', 'MALWARE', 'Virus, malware infection', (SELECT id FROM categories WHERE code = 'SECURITY'), 1),
('Phishing', 'PHISHING', 'Email lừa đảo, phishing', (SELECT id FROM categories WHERE code = 'SECURITY'), 2),
('Data Breach', 'BREACH', 'Nghi ngờ rò rỉ dữ liệu', (SELECT id FROM categories WHERE code = 'SECURITY'), 3),
('Permission Issue', 'PERMISSION', 'Vấn đề phân quyền bảo mật', (SELECT id FROM categories WHERE code = 'SECURITY'), 4);
