-- ============================================================
-- V38: Tạo bảng category_team_mapping cho auto-assignment
-- ============================================================

CREATE TABLE category_team_mapping (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT NOT NULL REFERENCES categories(id),
    team_id         BIGINT NOT NULL REFERENCES teams(id),
    priority        INT DEFAULT 0,  -- Ưu tiên nếu có nhiều mappings
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uk_category_team UNIQUE (category_id, team_id)
);

CREATE INDEX idx_category_team_category ON category_team_mapping(category_id);
CREATE INDEX idx_category_team_team ON category_team_mapping(team_id);
CREATE INDEX idx_category_team_priority ON category_team_mapping(priority);

COMMENT ON TABLE category_team_mapping IS 'Map category với team để auto-assign ticket';
COMMENT ON COLUMN category_team_mapping.priority IS 'Độ ưu tiên (số cao hơn = ưu tiên hơn)';

-- Seed default mappings (Category -> Team)
-- Priority: thấp nhất = round-robin, cao nhất = luôn assign vào team đó

-- Network Category -> Network Team
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 100
FROM categories c, teams t
WHERE c.code = 'NETWORK' AND t.code = 'NET';

-- Hardware Category -> Hardware Team
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 100
FROM categories c, teams t
WHERE c.code = 'HARDWARE' AND t.code = 'HW';

-- Software Category -> Software Team
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 100
FROM categories c, teams t
WHERE c.code = 'SOFTWARE' AND t.code = 'SW';

-- Security Category -> Security Team
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 100
FROM categories c, teams t
WHERE c.code = 'SECURITY' AND t.code = 'SEC';

-- Account & Email & Other -> General Support
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 50
FROM categories c, teams t
WHERE c.code IN ('ACCOUNT', 'EMAIL', 'OTHER') AND t.code = 'GEN';

-- Subcategories mapping (cụ thể hơn = priority cao hơn)
-- Wi-Fi -> Network Team
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 200
FROM categories c, teams t
WHERE c.code = 'WIFI' AND t.code = 'NET';

-- VPN -> Network Team
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 200
FROM categories c, teams t
WHERE c.code = 'VPN' AND t.code = 'NET';

-- Computer -> Hardware Team
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 200
FROM categories c, teams t
WHERE c.code = 'COMPUTER' AND t.code = 'HW';

-- Printer -> Hardware Team
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 200
FROM categories c, teams t
WHERE c.code = 'PRINTER' AND t.code = 'HW';

-- Installation -> Software Team
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 200
FROM categories c, teams t
WHERE c.code = 'INSTALL' AND t.code = 'SW';

-- Password Reset -> General Support (dễ xử lý)
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 200
FROM categories c, teams t
WHERE c.code = 'PASSWORD' AND t.code = 'GEN';

-- Malware/Virus -> Security Team (nghiêm trọng)
INSERT INTO category_team_mapping (category_id, team_id, priority) 
SELECT c.id, t.id, 200
FROM categories c, teams t
WHERE c.code = 'MALWARE' AND t.code = 'SEC';
