-- ============================================================
-- V39: Tạo bảng team_members cho việc quản lý thành viên team
-- ============================================================

CREATE TABLE team_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id         BIGINT NOT NULL REFERENCES teams(id),
    user_id         BIGINT NOT NULL REFERENCES users(id),
    role_in_team    VARCHAR(20) DEFAULT 'MEMBER',  -- MEMBER, LEAD, BACKUP
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uk_team_user UNIQUE (team_id, user_id)
);

CREATE INDEX idx_team_members_team ON team_members(team_id);
CREATE INDEX idx_team_members_user ON team_members(user_id);
CREATE INDEX idx_team_members_enabled ON team_members(enabled);

COMMENT ON TABLE team_members IS 'Thành viên của các team IT';
COMMENT ON COLUMN team_members.role_in_team IS 'Vai trò trong team: MEMBER, LEAD, BACKUP';

-- Seed default team members (IT staff vào các teams)
-- tech.smith vào Network Team
INSERT INTO team_members (team_id, user_id, role_in_team)
SELECT t.id, u.id, 'MEMBER'
FROM teams t, users u
WHERE t.code = 'NET' AND u.username = 'tech.smith';

-- tech.jane vào General Support (hoặc Software Team)
INSERT INTO team_members (team_id, user_id, role_in_team)
SELECT t.id, u.id, 'MEMBER'
FROM teams t, users u
WHERE t.code = 'GEN' AND u.username = 'tech.jane';
