-- ============================================================
-- V41: Tạo bảng notification_preferences
-- ============================================================

CREATE TABLE notification_preferences (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL REFERENCES users(id),
    notify_ticket_created   BOOLEAN NOT NULL DEFAULT TRUE,
    notify_ticket_assigned   BOOLEAN NOT NULL DEFAULT TRUE,
    notify_status_changed    BOOLEAN NOT NULL DEFAULT TRUE,
    notify_comment_added     BOOLEAN NOT NULL DEFAULT TRUE,
    notify_sla_warning      BOOLEAN NOT NULL DEFAULT TRUE,
    notify_sla_breached     BOOLEAN NOT NULL DEFAULT TRUE,
    notify_escalated        BOOLEAN NOT NULL DEFAULT TRUE,
    email_enabled           BOOLEAN NOT NULL DEFAULT TRUE,
    in_app_enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uk_user_preferences UNIQUE (user_id)
);

CREATE INDEX idx_notification_prefs_user ON notification_preferences(user_id);

COMMENT ON TABLE notification_preferences IS 'User notification preferences';
COMMENT ON COLUMN notification_preferences.notify_ticket_created IS 'Thông báo khi có ticket mới được tạo';
COMMENT ON COLUMN notification_preferences.notify_ticket_assigned IS 'Thông báo khi ticket được gán cho mình';
COMMENT ON COLUMN notification_preferences.notify_status_changed IS 'Thông báo khi status ticket thay đổi';
COMMENT ON COLUMN notification_preferences.notify_comment_added IS 'Thông báo khi có bình luận mới';
COMMENT ON COLUMN notification_preferences.notify_sla_warning IS 'Thông báo SLA warning';
COMMENT ON COLUMN notification_preferences.notify_sla_breached IS 'Thông báo SLA breach';
COMMENT ON COLUMN notification_preferences.notify_escalated IS 'Thông báo khi ticket được escalate';

-- Seed default preferences cho all users (sẽ dùng default TRUE)
INSERT INTO notification_preferences (user_id, email_enabled, in_app_enabled)
SELECT id, TRUE, TRUE FROM users WHERE approved = TRUE;
