-- ============================================================
-- V42: Thêm bảng cho SLA alert tracking
-- ============================================================

CREATE TABLE sla_alert_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id       BIGINT NOT NULL REFERENCES tickets(id),
    sla_type        VARCHAR(20) NOT NULL,  -- RESPONSE, RESOLUTION
    alert_type      VARCHAR(20) NOT NULL,  -- WARNING, BREACHED
    threshold_hours  INT NOT NULL,
    actual_hours    INT NOT NULL,
    notified        BOOLEAN NOT NULL DEFAULT FALSE,
    notified_at     TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uk_ticket_sla UNIQUE (ticket_id, sla_type, alert_type)
);

CREATE INDEX idx_sla_alert_ticket ON sla_alert_log(ticket_id);
CREATE INDEX idx_sla_alert_type ON sla_alert_log(alert_type);
CREATE INDEX idx_sla_alert_notified ON sla_alert_log(notified);

COMMENT ON TABLE sla_alert_log IS 'Track SLA alerts đã được gửi';
