-- ============================================================
-- V43: Tạo bảng ticket_timeline
-- ============================================================

CREATE TABLE ticket_timeline (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id       BIGINT NOT NULL REFERENCES tickets(id),
    event_type      VARCHAR(50) NOT NULL,  -- Xem enum EventType bên dưới
    event_category  VARCHAR(20) NOT NULL,  -- STATUS, ASSIGNMENT, COMMENT, SYSTEM, SLA
    title           VARCHAR(200) NOT NULL,
    description     VARCHAR(1000),
    
    -- Actor info (ai có thể là system hoặc user)
    actor_type      VARCHAR(20),          -- USER, SYSTEM
    actor_username  VARCHAR(80),
    actor_name      VARCHAR(120),
    actor_role      VARCHAR(20),
    
    -- Old/New values cho các thay đổi
    old_value       VARCHAR(500),
    new_value       VARCHAR(500),
    
    -- Additional data (JSON string cho flexibility)
    metadata        TEXT,
    
    created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_timeline_ticket ON ticket_timeline(ticket_id);
CREATE INDEX idx_timeline_type ON ticket_timeline(event_type);
CREATE INDEX idx_timeline_category ON ticket_timeline(event_category);
CREATE INDEX idx_timeline_created ON ticket_timeline(created_at DESC);

COMMENT ON TABLE ticket_timeline IS 'Lịch sử các sự kiện của ticket';
COMMENT ON COLUMN ticket_timeline.event_category IS 'Phân loại: STATUS, ASSIGNMENT, COMMENT, SYSTEM, SLA, CATEGORY, PRIORITY';
