CREATE TABLE ticket_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL,
  visibility VARCHAR(16) NOT NULL,
  body VARCHAR(2000) NOT NULL,
  actor_role VARCHAR(16) NOT NULL,
  actor_name VARCHAR(120),
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_ticket_comments_ticket
    FOREIGN KEY (ticket_id) REFERENCES tickets (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ticket_comments_ticket_id ON ticket_comments (ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_comments_visibility ON ticket_comments (visibility);
